# Generated by Django 4.1.5 on 2023-01-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="time",
            field=models.FloatField(),
        ),
    ]
