# Generated by Django 4.1.5 on 2023-01-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_alter_aesteticscores_first_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="nb_run",
            field=models.IntegerField(default=1),
        ),
    ]
