# Generated by Django 4.2.1 on 2023-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_rename_nb_run_run_num_run_alter_run_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='num_run',
            field=models.IntegerField(),
        ),
    ]
